src/SeafoodCod/Models/Marketing.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SeafoodCod.Models
{
    [Table("marketings")]
    public class Marketing
    {
        [Key]
        public int MarketingId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Img { get; set; }
       
       

    }
}

src/SeafoodCod/Controllers/MarketingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SeafoodCod.Models;
using Microsoft.AspNetCore.Identity;
using SeafoodCod.ViewModels;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace SeafoodCod.Controllers
{
    public class MarketingController : Controller
    {
        private ApplicationDbContext _db;

        public MarketingController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreateMarketing()
        {
            return View();
        }

        public IActionResult MarketingEdit()
        {
            return View();
        }

        
        }
    }

src/SeafoodCod/Views/Marketing/CreateMarketing.cshtml
@{
    ViewData["Title"] = "Add a Blog";
    Layout = "~/Views/Shared/_Layout5.cshtml";

}

@model SeafoodCod.Models.Marketing

@using System.Security.Claims

<div class="contact container-nav">
    <br />
    <h2 class="aboutP">SeafoodCod History</h2>
    @using (Html.BeginForm())
    {
        @Html.LabelFor(model => model.Title)
        @Html.TextBoxFor(model => model.Title)
        <br /><br />
        @Html.LabelFor(model => model.Description)
        @Html.TextAreaFor(model => model.Description)
        <br /><br />
        @Html.LabelFor(model => model.Img)
        @Html.TextBoxFor(model => model.Img)
        <br /><br />
       
        <br /><br />
        <input type="submit" value="CreateMarketing" class="btn btn-primary" />
    }
    <p>@Html.ActionLink("Back to Marketing Page", "Index", "Marketing")</p>
</div>

src/SeafoodCod/Views/Marketing/Index.cshtml
@{
    ViewData["Title"] = "Add a Blog";
    Layout = "~/Views/Shared/_Layout5.cshtml";

}

@using System.Security.Claims
@model SeafoodCod.Models.Marketing


    <div class="contact container-nav">
        <br />
        <h2 class="aboutP">SeafoodCod History</h2>
        <hr />
        <p>
            Welcome to SeafoodCod Market, a family owned & operated fish market providing a variety
            of fresh seafood including Homemade Seafood & Clam Chowders, live lobsters, shellfish, clams, shrimp,
            scallops, haddock, scrod, sole, salmon, swordfish, tuna, and much more, including seasonal specials!.
        </p>

        <h4><b>Partners:</b></h4>
        <p>
            Catalina Offshore Products is among 11 restaurant and retail businesses that have partnered
            with Seafood for the Future, whose mission is to encourage healthy and responsible seafood choices.
            As a result, Catalina Offshore Products is part of a network of businesses committed to sourcing
            better seafood choices from responsible fisheries or farms.
        </p>
    </div>

src/SeafoodCod/Views/Marketing/MarketingEdit.cshtml
@{
    ViewData["Title"] = "Add a Blog";
    Layout = "~/Views/Shared/_Layout4.cshtml";
}

@model SeafoodCod.Models.Marketing

@using (Html.BeginForm())
{
    <h2> Edit this Marketing: @Html.DisplayFor(model => model.Title)</h2>
    <hr />

        @using (Html.BeginForm())
        {
            @Html.HiddenFor(model => model.MarketingId)

            @Html.LabelFor(model => model.Title)
            @Html.EditorFor(model => model.Title)
            <br /><br />
            @Html.LabelFor(model => model.Img)
            @Html.EditorFor(model => model.Img)
            <br /><br />
            @Html.LabelFor(model => model.Description)
            @Html.TextAreaFor(model => model.Description)
            <br /><br />

            <input type="submit" value="Save" class="btn btn-primary" />

        }

}