src/SeafoodCod/Models/Newsletter.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
 // Creating this model "Newsletter" we are tying each newsletter to a user.//
// We are adding a new table "newsletters" to our DB, we need to add a newsletters Db set to our applicationDbContext.//
namespace SeafoodCod.Models
{
    [Table("newsletters")]
    public class Newsletter
    {
        [Key]
        public int NewsletterId { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public virtual ApplicationUser  User { get; set; }
    }
}

src/SeafoodCod/Controllers/NewsletterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using SeafoodCod.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Hosting;

// this controller is too manage our newsletter.

namespace SeafoodCod.Controllers
{
    // Authorize attribute allows access to the controller only if a user is logged in.
    [Authorize]
    public class NewsletterController : Controller
    {
        // Private instance of our Databse to work with, we need the userManager to work with users.
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IHostingEnvironment _environement;


        public NewsletterController (UserManager <ApplicationUser> userManager, ApplicationDbContext db, IHostingEnvironment environment)
        {
            
            _userManager = userManager;
            _db = db;
            _environement = environment;
        }

        public async Task<IActionResult> Index()
        {
            var id = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(id);
            return View(_db.Newsletters.Where(x => x.User.Id == currentUser.Id));
            
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Newsletter newsletter)
        {
            
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            var currentUser = await _userManager.FindByIdAsync(userId);

            newsletter.User = currentUser;
            _db.Newsletters.Add(newsletter);
            _db.SaveChanges();
            return RedirectToAction("Index");



        }
    }
}

src/SeafoodCod/Views/Newsletter/Create.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model SeafoodCod.Models.Newsletter
    
<div class="padding-huge"></div>

<h1>Sign up to our Newsletter</h1>
<hr />
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Email)
    @Html.EditorFor(model => model.Email)

    @Html.LabelFor(model => model.Country)
    @Html.EditorFor(model => model.Country)


    <input type="submit" value="Create" />
}

src/SeafoodCod/Views/Newsletter/Index.cshtml
@{
    ViewData["Title"] = "Add a Blog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using System.Security.Claims
@model IEnumerable<SeafoodCod.Models.Newsletter>

<section class="items-wrap">
<h1>Newsletter mailing list</h1>


@if (Model.Any())
{
    <ul>
        @foreach (var listNewsletter in Model)
        {
            <li>@Html.DisplayFor(modelNewsletter => listNewsletter.Email)</li>
            <li>@Html.DisplayFor(modelNewsletter => listNewsletter.Country)</li>

        }
    </ul>
}
else
{
    <p>Please Sign up to our Newsletter</p>
}
   </section>



@Html.ActionLink("NEWSLETTER SIGN UP", "Create", "Newsletter")